scoreboard players remove @s CraftSlot1 1
scoreboard players remove @s CraftSlot2 1
scoreboard players remove @s CraftSlot3 1
scoreboard players remove @s CraftSlot4 1
scoreboard players remove @s CraftSlot5 1
scoreboard players remove @s CraftSlot6 1
scoreboard players remove @s CraftSlot7 1
scoreboard players remove @s CraftSlot8 1
scoreboard players remove @s CraftSlot9 1